# -*- coding: utf-8 -*-
import os
import random

groups = {1: "Broods", 2: "Cash Cash", 3: "Colette Carr", 4: "Ellie Goulding",
		5: "Galantis", 6: "Illenium", 7: "Krewella", 8: "Lights", 9: "Melanie Martinez",
		10: "Owl City", 11: "Phoebe Ryan", 12: "Purity Ring", 13: "Tove Lo"}

lyrics = {"After we’re gone, Who will breathe the earth we lost": 6,
		"We're caught deep in the eye of the storm": 2,
		"Hold me like nobody else does, do I get the best of your love?": 4,
		"When I am fast asleep, I dream and see you floating high above me": 10,
		"Let's make this fleeting moment last forever, so tell me what you're waiting for?": 7,
		"Where was I when the rockets came to life, And carried you away into the alligator sky?": 10,
		"You're always aiming paper airplanes at me when you're around": 9,
		"Somberly, somberly, Linger lie longerly": 12,
		"Wake me if you're out there": 10,
		"I'll show you all of the places I'm dreaming of.": 4,
		"Stripped to the waist we fall into the river": 4,
		"I know that I've been messed up, You never let me give up": 4,
		"I just want to be around you, Is that too much to ask?": 4,
		"Eyes make their peace in difficulties, With wounded lips and salted cheeks": 4,
		"A spark soaring down through the pouring rain and restoring life to the lighthouse": 10,
		"I've been watching your kindness keep A lonely company, Look at the fire and think of me": 12,
		"Listen, I can hear the voice": 4,
		"Grandma my sleep is narrow, Bid you bring me some strong drink": 12,
		"If you're the bird, Whenever we pretend it's summer Then I'm the worm": 10,
		"So I walk alone, down the darkest roads, 'Cause I've always known how the story goes": 10,
		"Your arms around me come undone": 4,
		"You said, you said, Turn the lights down I wanna be alone": 12,
		"That blonde, she's a bomb, she's an atom bomb. Rigged up, and ready to drop!": 10,
		"Gave you a minute. When you needed an hour": 1,
		"There's a handwritten note pressed in the door of her screened in porch": 10,
		"We, we don't have to worry 'bout nothing": 4,
		"Your skin is warm like an oven. Your kiss is sugary sweet": 9,
		"We go river running, Deep blue indigo": 5,
		"La la la la Let's do something that we shouldn't do": 7,
		"All the thoughts in my head spin around like a hurricane": 10,
		"Look at it this way I am a boss": 3,
		"Mid air, I woke up beneath the flight deck, On the wall paper airplane": 10,
		"Round and round like a horse on a carousel, we go": 9,
		"Please take a long hard look through your text book, 'Cause I'm history": 10,
		"Chica chica, Chica Chica, Chica Chica": 3,
		"Best believe, you couldn't cure me if you tried": 11,
		"I can't remember, and I can't concentrate": 1,
		"boy you make it hard. Shouldn't need a riddle to unlock your heart": 4,
		"Pull my heart out of my chest, Train my mind so I'll forget": 7,
		"I'm coming up right out of the dark": 13,
		"Sea water's flowing from the middle of my thighs": 12,
		"You've seemed to replace your brain with your heart": 9,
		"Do you remember when you and I were young": 5,
		"I've made mistakes, been dishonest Self-estranged, did what I wanted": 11,
		"I regarded the world as such a sad sight. Until I viewed it in black and white": 10,
		"Met a girl in the parking lot, And all I did was say hello.": 10,
		"Every light in the night flickered in and out": 10,
		"I brush my teeth, and look in the mirror": 10,
		"Affection, the gifted architect, Is making a draft and beautiful design": 10,
		"Open up and let me in. Show the bruises on your skin": 4,
		"Hey girl, open the walls, play with your dolls. We'll be a perfect family.": 9,
		"Let’s keep on pretending that we’re nowhere, Creating everything as we go": 5,
		"I've been too numb to understand. I'm just a victim of the weapon in my hand": 4,
		"Bite down on your lip, Take another sip": 4,
		"We, were alone, on the road, driving faster": 10,
		"Splash down in the silver screen, Into a deep dramatic scene": 10,
		"Seems somebody put out the moon. Now the road is a mine field": 8,
		"Dear lie still along my old web, Cursed by your dust filled head": 12,
		"Good evening shuttle bus, Tell me where you're gonna take us": 10,
		"There were days. when each hour, was a war I fought to survive": 10,
		"We were born ready, ready to be free, Chasin' every thrill we could see": 7,
		"Lay by me, wrapped in evergreen": 1,
		"It starts with a picture, And it sits in your frame.": 4,
		"Are you with us darling? Cause you treat it like a game": 1,
		"Got me wrapped up in a zig zag, Got me thrown back like who the hell is that?": 3,
		"Can't control it but it's coming like a thunder in the sound.": 7,
		"Breathe your smoke into my lungs, In the back of a car with you I stare into the sun": 4,
		"Get a little closer let fold, Cut open my sternum, and pull My little ribs around you": 12,
		"Sittin on the finest, Kick it with the finest, Sippin on the finest": 3,
		"We, started at the cinema, T-roof dancing, hands in the wind": 5,
		"You would not believe your eyes, If ten million fireflies": 10,
		"Do you remember boy when you were so cruel?": 4,
		"She lost her voice down by the river": 12,
		"Let me call love blind tonight with, possibility": 5,
		"No light in the distance, We were shadows holding on": 6,
		"You walked in said I've got some news": 1,
		"I could take steps on this moon and that cloud": 8,
		"All those sun ups. Long days, short cuts": 8,
		"I'd lose everything so I can sing, Hallelujah, I'm free": 1,
		"Here in the open. Cool as a hand in the dark": 8,
		"Call back the cap com, Tick off the time bomb, Let felicity fly.": 10,
		"Stand on up and take a bow. There's something there and it's showing": 10,
		"Woke up on the right side of the bed": 10,
		"I lost a signal and put you away. Swore upon the sun I'd save you for a rainy day": 4,
		"When I breathe, and breathe into you, And I feel right to the bone": 13,
		"Just you and me. That true love, it was taken away from us so young": 4,
		"You're so quiet. But it doesn't faze me": 4,
		"I eat my dinner in my bathtub, Then I go to sex clubs": 13,
		"You know we can get away, 'Cause I'm calling your name": 4,
		"When you appeared I was just lonely, I was just in need of a friend": 4,
		"You wake up, I know it's time to go": 4,
		"Whisper, whimper on I, Won't forget to close your eyes for you": 12,
		"Hello Seattle, I am a mountaineer, In the hills and highlands": 10,
		"Swimming through the world, I wanna get all around": 2,
		"Hey Anna, he’s just a boy you won’t understand if you try": 10,
		"I won’t hide away, don’t try to lock me up": 2,
		"Enemy, used to be, Part of you, bittersweet, But now you tell me lies": 4,
		"Lonely thoughts they seep, into mind into me": 4,
		"I was lookin' for love when I lost it. Had a laundry list of others on the side": 11,
		"Don't remind me that some days I'm the windshield. And other days I'm just a lucky bug": 10,
		"We wrote a prelude. To our own fairy tale": 10,
		"How long will I love you?": 4,
		"Ask me a question, I only want to talk": 8,
		"Human, behave yourself, You have burst at the seams, Let it all fall out Open your mouth":4,
		"Is anybody there? Does anybody care What I'm feeling?": 7,
		"How many times do I need to, Need to fight you baby, Just to get that it's no good": 4,
		"I was so young and reckless. It was all a blur but there you were": 10,
		"She wound a thread around the pieces of my broken heart": 10,
		"I need your love, I need your time": 4,
		"Oh, so I'll be your reason. We won't talk again": 6,
		"Breathe air, you're not used to. Tread floors, you don't fall through": 4,
		"I saw your face in a criminal sketch. Don't be alarmed 'cause you don't know me yet": 10,
		"My mouth is frozen so I can't even speak. What a disappointment, I had it perfectly": 8,
		"You're the sky that I fell through. And I remember the view, Whenever I'm holding you": 10,
		"No I'm not tryin' to be rude but hey pretty girl I'm feelin' you": 11,
		"And if I ever had a wish In the whole world": 4,
		"Gasp for days but it's out of my hands": 5,
		"At first I didn't think that I was cut enough to bleed": 6,
		"The princess in her flower bed. Pulled the jungle underground": 10,
		"People like to talk because they don't know what to say": 4,
		"It's in the whispers of biology": 5,
		"You're gonna push your luck. Tell me you've had enough": 7,
		"You like to call me when I'm alone. Tell me that it's all for me": 1,
		"I'm tangled up, no strings attached. You gave your heart, but now I think you want it back": 3,
		"Well it's Christmas time, and i'm warm inside, despite the bitter cold": 10,
		"You and I. We could fly. Til we die": 2,
		"Kissing in the hallway. Turn off all the lights": 1,
		"I had a way then losing it all on my own": 4,
		"Hey boy, you're to young for me but I don't care 'cause you are all I see": 13,
		"If a plane crashed into my room I wouldn't even flinch": 4,
		"I live for the night, I live for the lights, I live for the high Til I'm free fallin'": 7,
		"Lead the way, and let's get it started. Seize the day, and reach for the sky": 10,
		"Gotta love this field and the cherry sky. Under blossom clouds though it's late July": 4,
		"Are you the one, from my side of town? Maybe, maybe": 5,
		"Chop off my hands. Chop off my feet. I'd do it for you. Ain't love sweet?": 13,
		"You're the light, you're the night. You're the color of my blood": 4,
		"It's you and I against the world hitting every green": 8,
		"My friends don't walk they run. Skinny dip in rabbit holes for fun": 9,
		"We got cups, we got drink. You got love, so do we!": 3,
		"I can finally see. That you're right there beside me": 10,
		"Perseids. Lead us out to where the money is": 8,
		"Oh oh, I can’t even take it in.": 10,
		"1, 2, melatonin is coming for you": 9,
		"When it went down. It was so hard to breathe": 11,
		"I grew up with a lot of green. Nice things round me, I was safe, I was fine": 13,
		"The nights are getting shorter I don't know where they go": 1,
		"If you weren't born with it, You can buy a couple ornaments": 9,
		"After having spent a fast year waiting for the next time I can get you close": 8,
		"You might know if you're from around here What goes on for half of the year": 8,
		"When my hope is lost and my strength is gone I run to You, and You alone": 10,
		"Heads turn your body burn rip off your clothes for me": 13,
		"It's like I slipped and fell, scrapped my knee": 3,
		"We got the green to the paper. And enough, green in the face, yeah": 3,
		"Sorry I ain't got no money I'm not trying to be funny but I left it all at home today": 5,
		"Shiny happy see my world in new colours?": 13,
		"I came down over the sleepy mountains": 12,
		"Gone when you get stuck, Sleeping when you wake up, Lover on the other coast": 8,
		"It's a little blurry how the whole thing started": 4,
		"Breathe, and I'll carry you away, into the velvet sky": 10,
		"Stay here... see me come undone. Just breathe my soul and turn me on": 7,
		"I guess I'll be the first to say it. I haven't felt this good in a while": 6,
		"Lovers, into friends. Move on, to strangers": 13,
		"Stay up 'til dawn I can't go home again now": 13,
		"Get down, get up again. Come on come on move!": 2,
		"Tired blue boy walks my way. Holding a girl's hand": 9,
		"I've been filling in the blanks You left me with your open hands": 4,
		"Touch you once, my fingers go numb Hold my breath one second too long": 13,
		"My heart feels drunk. I know that I don’t need anything else": 7,
		"If they take my hand. Will it be to burn me or to say 'Amen'?": 8,
		"Sleepless nights at the Chateau. Visualize it. I'll give you something to do": 5,
		"Did my invitations disappear? Why'd I put my heart on every cursive letter?": 9,
		"I saw a ghost on the stairs. And sheets on the tables and chairs": 10,
		"You call me on the telephone, you feel so far away": 9,
		"Somehow, you just took my breath away Took my breath away": 3,
		"Once in a while I act like a child, to feel like a kid again.": 8,
		"One night with me. Stay here if you can now baby": 1,
		"You were young and you'd stare With a reverence unimpaired": 12,
		"I'm not yours, and you're not mine But we can sit and pass the time": 8,
		"I saw the autumn leaves Peel up off the street": 10,
		"Tell me that you wanna move me around like that": 12,
		"When you're screaming out. But you can't make a sound You know. It's only a dream": 6,
		"the rules. I got nothing to lose": 7,
		"We run into a blazing fire We hold our heads up high tonight": 4,
		"Out across cities, I see buildings turn into piles": 8,
		"Toupee, or not toupee. That is the question": 10,
		"Think I can fly, think I can fly when I'm with you": 5,
		"We were kinda feral. Wicked little machines": 8,
		"You're as sharp as a knife and you fit like a glove": 4,
		"I opened my eyes last night. And saw you in the low light": 10,
		"Goin' the distance, every occasion, Headed for somewhere out of the way": 8,
		"We are, we are the satellites. All night we keep on moving": 2,
		"Scars we carry. Carry with memories Memories burned by the dark": 13,
		"I think I'll let fate just take me home. Because over pain love is outgrown": 4,
		"I could build a big machine. Draw pictures for the walls": 12,
		"How many times will the clock go 'round? How many times can my hands hit the ground?": 8,
		"Just before the dawn, When the light's still gone, Shine, shine your way": 10,
		"Close your tired eyes, Relax and then, Count from one to ten. And open them": 10,
		"From the busy parks To the icy tides": 8,
		"I'm tired of waking up in tears": 10,
		"Blood still stains when the sheets are washed": 9,
		"Sleep baby sleep What are you waiting for?": 1,
		"Sleepwalker, where do you go In the night": 6,
		"In the garden with the wild I can feel you like a child": 8,
		"Think I just remembered something. I think I left the faucet running": 9,
		"I am sober lying on my bed Recreating you inside my head": 1,
		"Its the strangest feeling, Feeling this way for you": 4,
		"I tried to disappear. But your the only reason I'm floating here": 10,
		"One by one, out the door, Wanted you, she wanted you oh": 8,
		"Remember when you asked me to paint you all my dreams": 6,
		"Handle bars, and then I let go, let go for anyone": 4,
		"Take my fate in your hands. We've got a lot that hasn't even began": 4,
		"Meet me in the blue bed I'll be drawing out your flaws": 12,
		"I had a feeling you broke and the smoke filled you up I wasn't thinkin' 'bout you": 12,
		"This is a world of dreams And reverie": 10,
		"So there we were, back home from somewhere inside my head": 10,
		"Glamor and fashion Models and magazines. a striking runway entrance": 10,
		"You've been looking for more I've been holding my head": 1,
		"I was running on an empty heart. Not a trace of gasoline": 2,
		"Somewhere we go to kill a while": 8,
		"Looking at me through your window, Boy you had your eye out for a little": 9,
		"There was a shot in the dark I was caught by surprise": 10,
		"I'm falling to pieces But I need this Yeah, I need this": 2,
		"Bed, stay in bed. The feeling of your skin locked in my head": 13,
		"Stitched you up, put you together With cotton and feather": 9,
		"You close your eyes And hope that nothing gets through": 7,
		"An eight year old girl had a panic attack": 10,
		"Who are we to be emotional? Who are we to play with hearts and throw away it all?": 4,
		"Too far away to feel you. But I can't forget your skin": 13,
		"I feel you glowing in the dark. When I collapse into your arms": 10,
		"I wish I could cross my arms and cross your mind": 10,
		"You made your way in as I was leaving You cut in line just as I was getting my stuff": 13,
		"You were walking in the sunset again without a hassle In the interim": 8,
		"Welcome back Winter once again": 10,
		"Shipwreck in the sea of faces, There's a dreamy world up there": 10,
		"Feels like I've been away for a thousand years": 10,
		"Riding down, riding down My hand on your seat The whole way round": 9,
		"It's unbelievable. This is as good as it gets": 10,
		"I'll never forget that feeling When I watched you disappear": 4,
		"Like all the boys before like all the boys boys boys boys": 4,
		"I fell in love with a ghost, out under the moonlight": 10,
		"Here. in a familiar place. We got our heads down": 8,
		"The stars lean down to kiss you": 10,
		"Ain't too sure what I believe in. But I believe in what I see": 10,
		"I'm just a victim trying to set myself free, but it's so hard to see you ain't right for me": 2,
		"So you're proud to be a good one. But the good ones always complain": 13,
		"I wanna go for a ride. Until the morning comes": 7,
		"Somewhere only we know, somewhere only we know": 3,
		"If we go down. We all go down together": 7,
		"Are you out there where the rainy days Began to feel rather sad": 10,
		"When can we do this again? When can I see you again?": 10,
		"He make me go bombay badawadaway bom bom": 3,
		"Why. O why are you leaving? When I desperately need you": 3,
		"Let's call it a day babe. I think I know what you're trying to say": 4,
		"Why can't we speak another language, one we all agree on?": 4,
		"You hate when my head, Hangs low after all": 6,
		"I feel you, Shutting down. After we've had one too many, Of these talks": 6,
		"It's another bad dream. Poison in my blood stream": 10,
		"You wait for a silence, I wait for a word": 4,
		"Hey, what's your name? 'Cause I need to know": 5,
		"Could have given me something. You my everything": 4,
		"Some days I barely hold on. When life drags me down. I wanna let go": 10,
		"Take cover. Signs don't show. You drove me off the road": 4,
		"Spot in the crowd, singin' loud I'd see her always hangin' around": 2
}

r1 = "say -v 'samantha' 'Way to go Burton'"
#r1 = "say -v 'samantha' 'Party on Zeus'"
#r2 = "say -v 'samantha' 'Bahama duck approves'"
#r3 = "say -v 'samantha' 'Jer Bear would be proud'"
#r4 = "say -v 'samantha' 'Nice job my little pastor boy'"
#r5 = "say -v 'samantha' 'Wow Nathan. I'm gonna be screaming a lot later on"
responses = [r1]
w = "say -v 'samantha' 'Cailin thats wrong. It's actually by "
q = "say -v 'samantha' \""
f = "say -v 'samantha' \"Cailin your final score is "
q2 = "... can you guess the artist?\""

print("GUESS THE ARTISTS!\n")

total = 0

keys = list(lyrics.keys())
random.shuffle(keys)


for lyric in keys:
	key = lyrics[lyric]
	print(lyric)
	os.system(q + lyric + q2)
	while (True):
		answer = input('Artist: ')
		if (answer.isdigit()):
			break
	a = int(answer)
	if (a == key):
		total += 1
		res = random.randrange(0,len(responses))
		os.system(responses[res])
	else:
		os.system(w + groups[key])
	print ("")
score = (total/len(lyrics))*100
os.system(f + str(total) + " out of " + str(len(lyrics)) + " which is a " + str(score) + " percent\"")

